/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LostRouteImport } from './routes/lost'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AtRiskRouteImport } from './routes/at-risk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowUpsIndexRouteImport } from './routes/follow-ups/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints/index'
import { Route as FollowUpsNewRouteImport } from './routes/follow-ups/new'
import { Route as FollowUpsIdRouteImport } from './routes/follow-ups/$id'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as ComplaintsIdRouteImport } from './routes/complaints/$id'
import { Route as AnalyticsRevenueRouteImport } from './routes/analytics/revenue'
import { Route as AnalyticsRetentionRouteImport } from './routes/analytics/retention'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskRoute = AtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsIndexRoute = FollowUpsIndexRouteImport.update({
  id: '/follow-ups/',
  path: '/follow-ups/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsNewRoute = FollowUpsNewRouteImport.update({
  id: '/follow-ups/new',
  path: '/follow-ups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsIdRoute = FollowUpsIdRouteImport.update({
  id: '/follow-ups/$id',
  path: '/follow-ups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRevenueRoute = AnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRetentionRoute = AnalyticsRetentionRouteImport.update({
  id: '/analytics/retention',
  path: '/analytics/retention',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/import': typeof ImportRoute
  '/lost': typeof LostRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/analytics/retention': typeof AnalyticsRetentionRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/follow-ups/$id': typeof FollowUpsIdRoute
  '/follow-ups/new': typeof FollowUpsNewRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/import': typeof ImportRoute
  '/lost': typeof LostRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/analytics/retention': typeof AnalyticsRetentionRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/follow-ups/$id': typeof FollowUpsIdRoute
  '/follow-ups/new': typeof FollowUpsNewRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/follow-ups': typeof FollowUpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/import': typeof ImportRoute
  '/lost': typeof LostRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/analytics/retention': typeof AnalyticsRetentionRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/follow-ups/$id': typeof FollowUpsIdRoute
  '/follow-ups/new': typeof FollowUpsNewRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/follow-ups/': typeof FollowUpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/at-risk'
    | '/import'
    | '/lost'
    | '/notifications'
    | '/onboarding'
    | '/revenue'
    | '/settings'
    | '/analytics/retention'
    | '/analytics/revenue'
    | '/complaints/$id'
    | '/customers/$id'
    | '/customers/new'
    | '/follow-ups/$id'
    | '/follow-ups/new'
    | '/complaints/'
    | '/customers/'
    | '/follow-ups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/at-risk'
    | '/import'
    | '/lost'
    | '/notifications'
    | '/onboarding'
    | '/revenue'
    | '/settings'
    | '/analytics/retention'
    | '/analytics/revenue'
    | '/complaints/$id'
    | '/customers/$id'
    | '/customers/new'
    | '/follow-ups/$id'
    | '/follow-ups/new'
    | '/complaints'
    | '/customers'
    | '/follow-ups'
  id:
    | '__root__'
    | '/'
    | '/at-risk'
    | '/import'
    | '/lost'
    | '/notifications'
    | '/onboarding'
    | '/revenue'
    | '/settings'
    | '/analytics/retention'
    | '/analytics/revenue'
    | '/complaints/$id'
    | '/customers/$id'
    | '/customers/new'
    | '/follow-ups/$id'
    | '/follow-ups/new'
    | '/complaints/'
    | '/customers/'
    | '/follow-ups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtRiskRoute: typeof AtRiskRoute
  ImportRoute: typeof ImportRoute
  LostRoute: typeof LostRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  AnalyticsRetentionRoute: typeof AnalyticsRetentionRoute
  AnalyticsRevenueRoute: typeof AnalyticsRevenueRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  FollowUpsIdRoute: typeof FollowUpsIdRoute
  FollowUpsNewRoute: typeof FollowUpsNewRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  FollowUpsIndexRoute: typeof FollowUpsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk': {
      id: '/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof AtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/': {
      id: '/follow-ups/'
      path: '/follow-ups'
      fullPath: '/follow-ups/'
      preLoaderRoute: typeof FollowUpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/new': {
      id: '/follow-ups/new'
      path: '/follow-ups/new'
      fullPath: '/follow-ups/new'
      preLoaderRoute: typeof FollowUpsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups/$id': {
      id: '/follow-ups/$id'
      path: '/follow-ups/$id'
      fullPath: '/follow-ups/$id'
      preLoaderRoute: typeof FollowUpsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/revenue': {
      id: '/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AnalyticsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/retention': {
      id: '/analytics/retention'
      path: '/analytics/retention'
      fullPath: '/analytics/retention'
      preLoaderRoute: typeof AnalyticsRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtRiskRoute: AtRiskRoute,
  ImportRoute: ImportRoute,
  LostRoute: LostRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  AnalyticsRetentionRoute: AnalyticsRetentionRoute,
  AnalyticsRevenueRoute: AnalyticsRevenueRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  FollowUpsIdRoute: FollowUpsIdRoute,
  FollowUpsNewRoute: FollowUpsNewRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  FollowUpsIndexRoute: FollowUpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
